export const questions4_9 = [
  {
    type: "sectionTitle",
    key: "definicionImplementacionControlesOperadores",
    title: "Definición e Implementación de Controles para Operadores",
  },
  {
    type: "radio",
    key: "definicionImplementacionControlesOperadoresPregunta",
    label: "¿La dependencia encargada de la operación estadística define e implementa los controles y acciones necesarios para asegurar que el operador subcontratado cumple con los requisitos establecidos en la norma y en cada iteración del proceso?",
    name: "definicionImplementacionControlesOperadoresPregunta",
    options: ["Sí", "No"],
    initialValue: "Sí",
  },
  {
    type: "checkbox",
    key: "definicionImplementacionControlesOperadoresContratacion",
    label: "Si la respuesta es Sí, ¿qué tipo de contratación se realiza con el operador? Seleccione todas las opciones que correspondan.",
    name: "definicionImplementacionControlesOperadoresContratacion",
    options: [
      "Contrato",
      "Alianza",
      "Convenio",
      "Acuerdo de nivel de servicio",
      "Otro",
    ],
    initialValue: [],
  },
  {
    type: "evidencias",
    key: "definicionImplementacionControlesOperadoresEvidencias",
    namePrefix: "definicionImplementacionControlesOperadores",
    fields: [
      { name: "definicionImplementacionControlesOperadoresEvidencia1", initialValue: "" },
      { name: "definicionImplementacionControlesOperadoresEvidencia2", initialValue: "" },
      { name: "definicionImplementacionControlesOperadoresEvidencia3", initialValue: "" },
    ],
  },
  {
    type: "sectionTitle",
    key: "responsabilidadProduccionEstadistica",
    title: "Responsabilidad de la Producción Estadística",
  },
  {
    type: "radio",
    key: "responsabilidadProduccionEstadisticaPregunta",
    label: "¿La dependencia encargada de la operación estadística mantiene la responsabilidad de la producción estadística aun cuando se subcontrate el desarrollo de fases o la producción total?",
    name: "responsabilidadProduccionEstadisticaPregunta",
    options: ["Sí", "No"],
    initialValue: "Sí",
  },
  {
    type: "evidencias",
    key: "responsabilidadProduccionEstadisticaEvidencias",
    namePrefix: "responsabilidadProduccionEstadistica",
    fields: [
      { name: "responsabilidadProduccionEstadisticaEvidencia1", initialValue: "" },
      { name: "responsabilidadProduccionEstadisticaEvidencia2", initialValue: "" },
      { name: "responsabilidadProduccionEstadisticaEvidencia3", initialValue: "" },
    ],
  },
  {
    type: "sectionTitle",
    key: "evaluacionSubcontratacion",
    title: "Evaluación de la Subcontratación",
  },
  {
    type: "slider",
    key: "evaluacionSubcontratacionPregunta",
    label: "Califique (1-5) qué tan efectiva es la dependencia encargada de la operación estadística en la definición e implementación de controles para los operadores subcontratados en el desarrollo de la operación estadística.",
    name: "evaluacionSubcontratacionPregunta",
    min: 1,
    max: 5,
    step: 1,
    initialValue: 2,
  },
  {
    type: "evidencias",
    key: "evaluacionSubcontratacionEvidencias",
    namePrefix: "evaluacionSubcontratacion",
    fields: [
      { name: "evaluacionSubcontratacionEvidencia1", initialValue: "" },
      { name: "evaluacionSubcontratacionEvidencia2", initialValue: "" },
      { name: "evaluacionSubcontratacionEvidencia3", initialValue: "" },
    ],
  },
  {
    type: "sectionTitle",
    key: "monitoreoCumplimientoRequisitos",
    title: "Monitoreo de Cumplimiento de Requisitos",
  },
  {
    type: "slider",
    key: "monitoreoCumplimientoRequisitosPregunta",
    label: "¿Cómo calificaría (1-5) la dependencia encargada de la operación estadística el monitoreo del cumplimiento de los requisitos por parte de los operadores subcontratados?",
    name: "monitoreoCumplimientoRequisitosPregunta",
    min: 1,
    max: 5,
    step: 1,
    initialValue: 2,
  },
  {
    type: "evidencias",
    key: "monitoreoCumplimientoRequisitosEvidencias",
    namePrefix: "monitoreoCumplimientoRequisitos",
    fields: [
      { name: "monitoreoCumplimientoRequisitosEvidencia1", initialValue: "" },
      { name: "monitoreoCumplimientoRequisitosEvidencia2", initialValue: "" },
      { name: "monitoreoCumplimientoRequisitosEvidencia3", initialValue: "" },
    ],
  },
  {
    type: "sectionTitle",
    key: "responsabilidadSubcontratacion",
    title: "Responsabilidad en la Subcontratación",
  },
  {
    type: "slider",
    key: "responsabilidadSubcontratacionPregunta",
    label: "¿Cómo evalúa (1-5) la dependencia encargada de la operación estadística su responsabilidad en la producción estadística, incluso cuando se subcontratan fases o la producción total?",
    name: "responsabilidadSubcontratacionPregunta",
    min: 1,
    max: 5,
    step: 1,
    initialValue: 2,
  },
  {
    type: "evidencias",
    key: "responsabilidadSubcontratacionEvidencias",
    namePrefix: "responsabilidadSubcontratacion",
    fields: [
      { name: "responsabilidadSubcontratacionEvidencia1", initialValue: "" },
      { name: "responsabilidadSubcontratacionEvidencia2", initialValue: "" },
      { name: "responsabilidadSubcontratacionEvidencia3", initialValue: "" },
    ],
  },
  {
    type: "sectionTitle",
    key: "sugerenciasSubcontratacion",
    title: "Sugerencias para Subcontratación para el Desarrollo de la Operación Estadística",
  },
  {
    type: "sugerencias",
    key: "sugerenciasSubcontratacionPregunta",
    label: "¿Tiene alguna sugerencia o comentario sobre cómo la entidad podría mejorar la identificación, documentación y actualización de los usuarios y sus necesidades de información estadística?",
    name: "sugerenciasSubcontratacionPregunta",
    initialValue: "",
  },
  {
    type: "sectionTitle",
    key: "accionesRequeridas",
    title: "Acciones requeridas",
  },
  {
    type: "accionesRequeridas",
    key: "accionesRequeridas",
    fields: [
      { name: "accion", initialValue: "" },
      { name: "responsableSNS", initialValue: "" },
      { name: "fechaCumplimiento", initialValue: "" },
    ],
  },
];
