// ./src/questions/questions4/questions4_1.js

export const questions4_1 = [
  {
    type: "sectionTitle",
    key: "sectionResponsabilidadRecursos",
    title: "Responsabilidad de Proporcionar Recursos",
  },
  {
    type: "radio",
    key: "respRecursosPregunta1",
    label: "¿La Alta Dirección proporciona los recursos necesarios para implementar lo establecido en la normativa vigente?",
    name: "respRecursosPregunta1",
    options: ["Sí", "No", "No Aplica"],
    initialValue: "Sí",
  },
  {
    type: "checkbox",
    key: "respRecursosPregunta2",
    label: "Si la respuesta es Sí, ¿La entidad asegura la disponibilidad de recursos adecuados para las siguientes áreas? (Seleccione todas las que apliquen)",
    name: "respRecursosPregunta2",
    options: [
      "Implementación de la Norma Técnica de la Calidad del Proceso Estadístico",
      "Mantenimiento y mejora del proceso estadístico",
      "Compromiso con la transparencia, la confidencialidad y la imparcialidad",
      "Continuidad de la operación estadística",
    ],
    initialValue: [],
  },
  {
    type: "evidencias",
    key: "respRecursosEvidencias",
    namePrefix: "respRecursos",
    fields: [
      { name: "respRecursosEvidencia1", initialValue: "" },
      { name: "respRecursosEvidencia2", initialValue: "" },
      { name: "respRecursosEvidencia3", initialValue: "" },
    ],
  },
  {
    type: "sectionTitle",
    key: "sectionResponsabilidadMejora",
    title: "Responsabilidad en la Mejora del Proceso Estadístico",
  },
  {
    type: "radio",
    key: "respMejoraPregunta1",
    label: "¿La alta dirección mantiene y mejora el proceso estadístico de acuerdo con el marco legal y las funciones de la entidad?",
    name: "respMejoraPregunta1",
    options: ["Sí", "No"],
    initialValue: "Sí",
  },
  {
    type: "slider",
    key: "evaluacionPregunta1",
    label: "Califique (1-5) qué tan efectiva es la alta dirección en proporcionar los recursos necesarios y mantener el compromiso con la normativa y el proceso estadístico:",
    name: "evaluacionPregunta1",
    min: 1,
    max: 5,
    step: 1,
    initialValue: 3,
  },
  {
    type: "evidencias",
    key: "respMejoraEvidencias",
    namePrefix: "respMejora",
    fields: [
      { name: "respMejoraEvidencia1", initialValue: "" },
      { name: "respMejoraEvidencia2", initialValue: "" },
      { name: "respMejoraEvidencia3", initialValue: "" },
    ],
  },
  {
    type: "sectionTitle",
    key: "sectionAsignacionRoles",
    title: "Asignación y Comunicación de Roles y Responsabilidades",
  },
  {
    type: "radio",
    key: "asignacionPregunta1",
    label: "¿La Alta Dirección proporciona los recursos necesarios para implementar lo establecido en la normativa vigente?",
    name: "asignacionPregunta1",
    options: ["Sí", "No", "No Aplica"],
    initialValue: "Sí",
  },
  {
    type: "checkbox",
    key: "asignacionPregunta2",
    label: "Si la respuesta es Sí, ¿La entidad asegura la disponibilidad de recursos adecuados para las siguientes áreas? (Seleccione todas las que apliquen)",
    name: "asignacionPregunta2",
    options: [
      "Roles específicos",
      "Responsabilidades correspondientes",
      "Cumplimiento de requisitos",
    ],
    initialValue: [],
  },
  {
    type: "evidencias",
    key: "asignacionEvidencias",
    namePrefix: "asignacion",
    fields: [
      { name: "asignacionEvidencia1", initialValue: "" },
      { name: "asignacionEvidencia2", initialValue: "" },
      { name: "asignacionEvidencia3", initialValue: "" },
    ],
  },
  {
    type: "sectionTitle",
    key: "sectionEvaluacionResponsabilidad",
    title: "Evaluación de la Responsabilidad de la Alta Dirección",
  },
  {
    type: "slider",
    key: "evaluacionPregunta2",
    label: "Califique (1-5) qué tan efectiva es la alta dirección en proporcionar los recursos necesarios y mantener el compromiso con la normativa y el proceso estadístico:",
    name: "evaluacionPregunta2",
    min: 1,
    max: 5,
    step: 1,
    initialValue: 3,
  },
  {
    type: "evidencias",
    key: "evaluacionEvidencias",
    namePrefix: "evaluacion",
    fields: [
      { name: "evaluacionEvidencia1", initialValue: "" },
      { name: "evaluacionEvidencia2", initialValue: "" },
      { name: "evaluacionEvidencia3", initialValue: "" },
    ],
  },
  {
    type: "sectionTitle",
    key: "sectionSugerencias",
    title: "Sugerencias para Responsabilidades de la Alta Dirección",
  },
  {
    type: "sugerencias",
    key: "sugerenciasComentario",
    label: "¿Tiene alguna sugerencia o comentario sobre cómo la entidad podría mejorar la identificación, documentación y actualización de los usuarios y sus necesidades de información estadística?",
    name: "sugerenciasComentarioField",
    initialValue: "",
  },
  {
    type: "sectionTitle",
    key: "sectionAccionesRequeridas",
    title: "Acciones requeridas",
  },
  {
    type: "accionesRequeridas",
    key: "accionesRequeridas",
    fields: [
      { name: "accion", initialValue: "" },
      { name: "responsableSNS", initialValue: "" },
      { name: "fechaCumplimiento", initialValue: "" },
    ],
  },
];
