// ./../../../questions/operation_questions.js

export const operationQuestions = [
  {
    type: "input",
    key: "nombreOperacion",
    label: "Nombre de la Operación Estadística",
    name: "nombreOperacion",
    placeholder: "Ingrese el nombre",
    initialValue: "",
  },
  {
    type: "select",
    key: "dependencia",
    label: "Dependencia Encargada",
    name: "dependencia",
    options: [
      { value: "direccion", label: "Dirección de Innovación y Desarrollo" },
      { value: "subdireccion", label: "Subdirección de Analítica" },
      { value: "ti", label: "Subdirección de TI" },
      { value: "interno", label: "Control Interno" },
      { value: "metodologia", label: "Subdirección de Metodología" },
    ],
    initialValue: "direccion",
  },
  {
    type: "radio",
    key: "registroAdmin",
    label: "¿La operación se presenta como un registro administrativo?",
    name: "registroAdmin",
    options: ["Sí", "No"],
    initialValue: "1",
  },
  {
    type: "input",
    key: "objetivo",
    label: "Objetivo de la Operación",
    name: "objetivo",
    placeholder: "Describe el objetivo",
    initialValue: "",
  },
  {
    type: "input",
    key: "poblacion",
    label: "Población Objetivo",
    name: "poblacion",
    placeholder: "Describe la población objetivo",
    initialValue: "",
  },
  {
    type: "date",
    key: "anioInicio",
    label: "Año de Inicio",
    name: "anioInicio",
    initialValue: "",
  },
  {
    type: "select",
    key: "areaTematica",
    label: "Área Temática",
    name: "areaTematica",
    options: [
      { value: "economica", label: "Económica" },
      { value: "sociodemografica", label: "Sociodemográfica" },
      { value: "ambiental", label: "Ambiental" },
    ],
    initialValue: "",
  },
  {
    type: "input",
    key: "periodicidad",
    label: "Periodicidad de la Operación Estadística",
    name: "periodicidad",
    placeholder: "Ejemplo: Mensual, Anual",
    initialValue: "",
  },
  {
    type: "select",
    key: "unidadEstudio",
    label: "Unidades de Estudio",
    name: "unidadEstudio",
    options: [
      { value: "Personas", label: "Personas" },
      { value: "IPS", label: "IPS" },
      { value: "EAPB", label: "EAPB" },
      { value: "Otras", label: "Otras" },
    ],
    initialValue: "",
  },
  {
    type: "input",
    key: "variablesPrincipales",
    label: "Variables Principales",
    name: "variablesPrincipales",
    placeholder: "Ingrese sugerencias",
    initialValue: "",
  },
  {
    type: "input",
    key: "coberturaGeografica",
    label: "Cobertura Geográfica",
    name: "coberturaGeografica",
    placeholder: "Ingrese cobertura geográfica",
    initialValue: "",
  },
  {
    type: "input",
    key: "periodoReferencia",
    label: "Período de Referencia",
    name: "periodoReferencia",
    placeholder: "Ingrese período de referencia",
    initialValue: "",
  },
  {
    type: "input",
    key: "metodoRecoleccion",
    label: "Método de Recolección de Información",
    name: "metodoRecoleccion",
    placeholder: "Ingrese método de recolección",
    initialValue: "",
  },
];
