export const questions4_10 = [
  {
    type: "sectionTitle",
    key: "definicionMecanismosSeguimientoMedicion",
    title: "Definición de Mecanismos de Seguimiento y Medición",
  },
  {
    type: "checkbox",
    key: "definicionMecanismosSeguimientoMedicionPregunta",
    label: "¿La dependencia encargada de la operación estadística define mecanismos de seguimiento y medición en cada fase del proceso estadístico para asegurar que la operación estadística:",
    name: "definicionMecanismosSeguimientoMedicionPregunta",
    options: [
      "Cumple los objetivos establecidos",
      "Cumple con la metodología",
      "Es oportuna en la generación y difusión de información estadística",
      "Identifica mejoras y lecciones aprendidas",
    ],
    initialValue: [],
  },
  {
    type: "evidencias",
    key: "definicionMecanismosSeguimientoMedicionEvidencias",
    namePrefix: "definicionMecanismosSeguimientoMedicion",
    fields: [
      { name: "definicionMecanismosSeguimientoMedicionEvidencia1", initialValue: "" },
      { name: "definicionMecanismosSeguimientoMedicionEvidencia2", initialValue: "" },
      { name: "definicionMecanismosSeguimientoMedicionEvidencia3", initialValue: "" },
    ],
  },
  {
    type: "sectionTitle",
    key: "determinacionSeguimientoMedicion",
    title: "Determinación del Seguimiento y Medición",
  },
  {
    type: "checkbox",
    key: "determinacionSeguimientoMedicionPregunta",
    label: "¿La dependencia encargada de la operación estadística determina:",
    name: "determinacionSeguimientoMedicionPregunta",
    options: [
      "La necesidad de seguimiento para cada fase del proceso estadístico",
      "Cuándo y quién realiza el seguimiento y la medición",
      "Cuándo y quién analiza y evalúa los resultados del seguimiento y la medición",
    ],
    initialValue: [],
  },
  {
    type: "evidencias",
    key: "determinacionSeguimientoMedicionEvidencias",
    namePrefix: "determinacionSeguimientoMedicion",
    fields: [
      { name: "determinacionSeguimientoMedicionEvidencia1", initialValue: "" },
      { name: "determinacionSeguimientoMedicionEvidencia2", initialValue: "" },
      { name: "determinacionSeguimientoMedicionEvidencia3", initialValue: "" },
    ],
  },
  {
    type: "sectionTitle",
    key: "documentacionMecanismosSeguimientoMedicion",
    title: "Documentación de Mecanismos de Seguimiento y Medición",
  },
  {
    type: "slider",
    key: "documentacionMecanismosSeguimientoMedicionPregunta",
    label: "Califique (1-5) qué tan efectiva es la dependencia encargada de la operación estadística en conservar la evidencia de los mecanismos de seguimiento y medición.",
    name: "documentacionMecanismosSeguimientoMedicionPregunta",
    min: 1,
    max: 5,
    step: 1,
    initialValue: 3,
  },
  {
    type: "evidencias",
    key: "documentacionMecanismosSeguimientoMedicionEvidencias",
    namePrefix: "documentacionMecanismosSeguimientoMedicion",
    fields: [
      { name: "documentacionMecanismosSeguimientoMedicionEvidencia1", initialValue: "" },
      { name: "documentacionMecanismosSeguimientoMedicionEvidencia2", initialValue: "" },
      { name: "documentacionMecanismosSeguimientoMedicionEvidencia3", initialValue: "" },
    ],
  },
  {
    type: "sectionTitle",
    key: "pruebasEvaluacion",
    title: "Pruebas y Evaluación",
  },
  {
    type: "checkbox",
    key: "pruebasEvaluacionPregunta",
    label: "¿La dependencia encargada de la operación estadística garantiza que se realicen las pruebas y la evaluación en las siguientes fases?",
    name: "pruebasEvaluacionPregunta",
    options: [
      "Diseño y construcción",
      "Recolección o acopio",
      "Procesamiento",
      "Análisis",
      "Difusión",
    ],
    initialValue: [],
  },
  {
    type: "evidencias",
    key: "pruebasEvaluacionEvidencias",
    namePrefix: "pruebasEvaluacion",
    fields: [
      { name: "pruebasEvaluacionEvidencia1", initialValue: "" },
      { name: "pruebasEvaluacionEvidencia2", initialValue: "" },
      { name: "pruebasEvaluacionEvidencia3", initialValue: "" },
    ],
  },
  {
    type: "sectionTitle",
    key: "accionesCorrectivasEficacia",
    title: "Acciones Correctivas y Eficacia",
  },
  {
    type: "sugerencias",
    key: "accionesCorrectivasEficaciaPregunta",
    label: "¿Cómo evalúa la dependencia encargada de la operación estadística la toma de acciones y la garantía de su eficacia, teniendo en cuenta las conclusiones de las pruebas y la evaluación?",
    name: "accionesCorrectivasEficaciaPregunta",
    initialValue: "",
  },
  {
    type: "evidencias",
    key: "accionesCorrectivasEficaciaEvidencias",
    namePrefix: "accionesCorrectivasEficacia",
    fields: [
      { name: "accionesCorrectivasEficaciaEvidencia1", initialValue: "" },
      { name: "accionesCorrectivasEficaciaEvidencia2", initialValue: "" },
      { name: "accionesCorrectivasEficaciaEvidencia3", initialValue: "" },
    ],
  },
  {
    type: "sectionTitle",
    key: "sugerenciasSeguimientoMedicion",
    title: "Sugerencias para el Seguimiento y Medición",
  },
  {
    type: "sugerencias",
    key: "sugerenciasSeguimientoMedicionPregunta",
    label: "¿Tiene alguna sugerencia o comentario sobre cómo la entidad podría mejorar el seguimiento y la medición de los indicadores de calidad, eficiencia y efectividad en el proceso estadístico?",
    name: "sugerenciasSeguimientoMedicionPregunta",
    initialValue: "",
  },
  {
    type: "sectionTitle",
    key: "accionesRequeridas",
    title: "Acciones requeridas",
  },
  {
    type: "accionesRequeridas",
    key: "accionesRequeridas",
    fields: [
      { name: "accion", initialValue: "" },
      { name: "responsableSNS", initialValue: "" },
      { name: "fechaCumplimiento", initialValue: "" },
    ],
  },
];
