export const questions4_2 = [
  {
    type: "sectionTitle",
    key: "estructuraOrganica",
    title: "Estructura Orgánica",
  },
  {
    type: "radio",
    key: "estructuraOrganicaPregunta1",
    label: "¿La entidad cuenta con una estructura orgánica documentada?",
    name: "estructuraOrganicaPregunta1",
    options: ["Sí", "No"],
    initialValue: "",
  },
  {
    type: "evidencias",
    key: "estructuraOrganicaEvidencias",
    namePrefix: "estructuraOrganica",
    fields: [
      { name: "estructuraOrganicaEvidencia1", initialValue: "" },
      { name: "estructuraOrganicaEvidencia2", initialValue: "" },
      { name: "estructuraOrganicaEvidencia3", initialValue: "" },
    ],
  },
  {
    type: "sectionTitle",
    key: "documentacionActividades",
    title: "Documentación de Actividades",
  },
  {
    type: "radio",
    key: "documentacionActividadesPregunta1",
    label: "¿La entidad tiene documentada, implementada y actualizada la información requerida para desarrollar las diferentes actividades conforme a los requisitos de esta norma?",
    name: "documentacionActividadesPregunta1",
    options: ["Sí", "No"],
    initialValue: "",
  },
  {
    type: "radio",
    key: "documentacionActividadesPregunta2",
    label: "Si la respuesta es Sí, ¿incluye esta documentación evidencia de los controles para asegurar la calidad del proceso estadístico?",
    name: "documentacionActividadesPregunta2",
    options: ["Sí", "No"],
    initialValue: "",
  },
  {
    type: "evidencias",
    key: "documentacionActividadesEvidencias",
    namePrefix: "documentacionActividades",
    fields: [
      { name: "documentacionActividadesEvidencia1", initialValue: "" },
      { name: "documentacionActividadesEvidencia2", initialValue: "" },
      { name: "documentacionActividadesEvidencia3", initialValue: "" },
    ],
  },
  {
    type: "sectionTitle",
    key: "infraestructuraProceso",
    title: "Infraestructura para el Proceso Estadístico",
  },
  {
    type: "radio",
    key: "infraestructuraPregunta1",
    label: "¿La entidad cuenta con la infraestructura necesaria para el proceso estadístico, incluyendo edificios, equipos, recursos de transporte, tecnologías de la información y comunicación, y otros recursos?",
    name: "infraestructuraPregunta1",
    options: ["Sí", "No"],
    initialValue: "",
  },
  {
    type: "radio",
    key: "infraestructuraPregunta2",
    label: "Si la respuesta es Sí, ¿están documentados, implementados y actualizados todos estos aspectos?",
    name: "infraestructuraPregunta2",
    options: ["Sí", "No"],
    initialValue: "",
  },
  {
    type: "evidencias",
    key: "infraestructuraEvidencias",
    namePrefix: "infraestructura",
    fields: [
      { name: "infraestructuraEvidencia1", initialValue: "" },
      { name: "infraestructuraEvidencia2", initialValue: "" },
      { name: "infraestructuraEvidencia3", initialValue: "" },
    ],
  },
  {
    type: "sectionTitle",
    key: "mecanismosCooperacion",
    title: "Mecanismos de Cooperación",
  },
  {
    type: "radio",
    key: "mecanismosCooperacionPregunta1",
    label: "¿La entidad desarrolla y gestiona mecanismos de cooperación con organismos pares para fortalecer la producción estadística?",
    name: "mecanismosCooperacionPregunta1",
    options: ["Sí", "No"],
    initialValue: "",
  },
  {
    type: "evidencias",
    key: "mecanismosCooperacionEvidencias",
    namePrefix: "mecanismosCooperacion",
    fields: [
      { name: "mecanismosCooperacionEvidencia1", initialValue: "" },
      { name: "mecanismosCooperacionEvidencia2", initialValue: "" },
      { name: "mecanismosCooperacionEvidencia3", initialValue: "" },
    ],
  },
  {
    type: "sectionTitle",
    key: "documentacionControles",
    title: "Documentación de Controles",
  },
  {
    type: "slider",
    key: "documentacionControlesPregunta1",
    label: "¿Califique (1-5) qué tan efectiva es la entidad en documentar, implementar y actualizar las evidencias de los controles llevados a cabo para asegurar la calidad del proceso estadístico?",
    name: "documentacionControlesPregunta1",
    min: 1,
    max: 5,
    step: 1,
    initialValue: 3,
  },
  {
    type: "evidencias",
    key: "documentacionControlesEvidencias",
    namePrefix: "documentacionControles",
    fields: [
      { name: "documentacionControlesEvidencia1", initialValue: "" },
      { name: "documentacionControlesEvidencia2", initialValue: "" },
      { name: "documentacionControlesEvidencia3", initialValue: "" },
    ],
  },
  {
    type: "sectionTitle",
    key: "sugerenciasResponsabilidad",
    title: "Sugerencias para Responsabilidades de la Alta Dirección",
  },
  {
    type: "sugerencias",
    key: "sugerenciasAltaDireccion",
    label: "¿Tiene alguna sugerencia o comentario sobre cómo la entidad podría mejorar la identificación, documentación y actualización de los usuarios y sus necesidades de información estadística?",
    name: "sugerenciasAltaDireccion",
    initialValue: "",
  },
  {
    type: "sectionTitle",
    key: "accionesRequeridas",
    title: "Acciones requeridas",
  },
  {
    type: "accionesRequeridas",
    key: "accionesRequeridas4_2",
    fields: [
      { name: "accion", initialValue: "" },
      { name: "responsableSNS", initialValue: "" },
      { name: "fechaCumplimiento", initialValue: "" },
    ],
  },
];
