export const questions4_3 = [
  {
    type: "sectionTitle",
    key: "confidencialidadDatos",
    title: "Confidencialidad de Datos Recolectados e Información Estadística",
  },
  {
    type: "radio",
    key: "confidencialidadMecanismos",
    label: "¿La dependencia encargada de la operación estadística ha implementado mecanismos que garantizan que los datos recolectados y la información estadística producida se conserven de manera confidencial conforme a la normatividad vigente de protección de datos personales y los Principios Fundamentales de las Estadísticas Oficiales de Naciones Unidas?",
    name: "confidencialidadMecanismos",
    options: ["Sí", "No", "No Aplica"],
    initialValue: "Sí",
  },
  {
    type: "evidencias",
    key: "confidencialidadEvidencias",
    namePrefix: "confidencialidad",
    fields: [
      { name: "confidencialidadEvidencia1", initialValue: "" },
      { name: "confidencialidadEvidencia2", initialValue: "" },
      { name: "confidencialidadEvidencia3", initialValue: "" },
    ],
  },
  {
    type: "sectionTitle",
    key: "conservacionSeguraDatos",
    title: "Conservación Segura de Datos",
  },
  {
    type: "radio",
    key: "conservacionSegura",
    label: "¿La entidad conserva los datos recolectados de forma segura para prevenir el acceso o uso no deseado, daños o pérdida fortuita?",
    name: "conservacionSegura",
    options: ["Sí", "No", "No Aplica"],
    initialValue: "Sí",
  },
  {
    type: "evidencias",
    key: "conservacionEvidencias",
    namePrefix: "conservacion",
    fields: [
      { name: "conservacionEvidencia1", initialValue: "" },
      { name: "conservacionEvidencia2", initialValue: "" },
      { name: "conservacionEvidencia3", initialValue: "" },
    ],
  },
  {
    type: "sectionTitle",
    key: "efectividadConservacion",
    title: "Efectividad en la Conservación de Datos",
  },
  {
    type: "slider",
    key: "efectividadConservacion",
    label: "Califique (1-5) ¿Qué tan efectiva es la entidad en conservar los datos recolectados de manera segura, garantizando su confidencialidad?",
    name: "efectividadConservacion",
    min: 1,
    max: 5,
    step: 1,
    initialValue: 2,
  },
  {
    type: "evidencias",
    key: "efectividadEvidencias",
    namePrefix: "efectividad",
    fields: [
      { name: "efectividadEvidencia1", initialValue: "" },
      { name: "efectividadEvidencia2", initialValue: "" },
      { name: "efectividadEvidencia3", initialValue: "" },
    ],
  },
  {
    type: "sectionTitle",
    key: "cumplimientoNormatividad",
    title: "Cumplimiento con Normatividad de Protección de Datos",
  },
  {
    type: "slider",
    key: "cumplimientoNormatividad",
    label: "Califique (1-5) ¿En qué medida la entidad cumple con la normatividad vigente de protección de datos personales y los Principios Fundamentales de las Estadísticas Oficiales de Naciones Unidas en la gestión de datos recolectados?",
    name: "cumplimientoNormatividad",
    min: 1,
    max: 5,
    step: 1,
    initialValue: 2,
  },
  {
    type: "evidencias",
    key: "cumplimientoEvidencias",
    namePrefix: "cumplimiento",
    fields: [
      { name: "cumplimientoEvidencia1", initialValue: "" },
      { name: "cumplimientoEvidencia2", initialValue: "" },
      { name: "cumplimientoEvidencia3", initialValue: "" },
    ],
  },
  {
    type: "sectionTitle",
    key: "prevencionAccesoPerdida",
    title: "Prevención de Acceso No Deseado y Pérdida de Datos",
  },
  {
    type: "textarea",
    key: "prevencionAccesoPerdida",
    label: "¿Cómo evalúa la entidad las medidas implementadas para prevenir el acceso o uso no deseado, daños o pérdida fortuita de los datos recolectados?",
    name: "prevencionAccesoPerdida",
    placeholder: "Ingrese su evaluación",
    rows: 4,
    initialValue: "",
  },
  {
    type: "evidencias",
    key: "prevencionEvidencias",
    namePrefix: "prevencion",
    fields: [
      { name: "prevencionEvidencia1", initialValue: "" },
      { name: "prevencionEvidencia2", initialValue: "" },
      { name: "prevencionEvidencia3", initialValue: "" },
    ],
  },
  {
    type: "sectionTitle",
    key: "sugerenciasConfidencialidad",
    title: "Sugerencias para Confidencialidad de Datos Recolectados e Información Estadística",
  },
  {
    type: "sugerencias",
    key: "sugerenciasConfidencialidad",
    label: "¿Tiene alguna sugerencia o comentario sobre cómo la entidad podría mejorar la identificación, documentación y actualización de los usuarios y sus necesidades de información estadística?",
    name: "sugerenciasConfidencialidad",
    initialValue: "",
  },
  {
    type: "sectionTitle",
    key: "accionesRequeridas",
    title: "Acciones requeridas",
  },
  {
    type: "accionesRequeridas",
    key: "accionesRequeridas",
    fields: [
      { name: "accion", initialValue: "" },
      { name: "responsableSNS", initialValue: "" },
      { name: "fechaCumplimiento", initialValue: "" },
    ],
  },
];
