export const questions5_3 = [
  {
    type: "sectionTitle",
    key: "identificacionRelevancia",
    title: "Identificación de Relevancia",
  },
  {
    type: "radio",
    key: "identificacionRelevanciaPregunta",
    label: "¿La dependencia encargada de la operación estadística identifica y documenta adecuadamente la relevancia de la operación estadística y su relación con la política pública?",
    name: "identificacionRelevanciaPregunta",
    options: ["Sí", "No"],
    initialValue: "Sí",
  },
  {
    type: "checkbox",
    key: "identificacionRelevanciaEvidencia",
    label: "Si la respuesta es Sí, la relevancia está evidenciada a través de:",
    name: "identificacionRelevanciaEvidencia",
    options: [
      "Leyes, decretos, resoluciones",
      "Plan Nacional de Desarrollo",
      "Documentos del CONPES",
      "Planes de Desarrollo Territoriales",
      "Acuerdos internacionales",
      "Plan Estadístico Nacional",
      "Documentos de política pública",
    ],
    initialValue: [],
  },
  {
    type: "evidencias",
    key: "identificacionRelevanciaEvidencias",
    namePrefix: "identificacionRelevancia",
    fields: [
      { name: "identificacionRelevanciaEvidencia1", initialValue: "" },
      { name: "identificacionRelevanciaEvidencia2", initialValue: "" },
      { name: "identificacionRelevanciaEvidencia3", initialValue: "" },
    ],
  },
  {
    type: "sectionTitle",
    key: "documentacionRelevancia",
    title: "Documentación de Relevancia",
  },
  {
    type: "radio",
    key: "documentacionRelevanciaPregunta",
    label: "¿La dependencia encargada de la operación estadística evidencia la relevancia de la información estadística en términos de su importancia para el país?",
    name: "documentacionRelevanciaPregunta",
    options: ["Sí", "No"],
    initialValue: "Sí",
  },
  {
    type: "slider",
    key: "documentacionRelevanciaCalificacion",
    label: "Si la respuesta es Sí, califique (1-5) ¿Qué tan efectiva es la dependencia encargada de la operación estadística en identificar y documentar la relevancia de la operación estadística en relación con la política pública?",
    name: "documentacionRelevanciaCalificacion",
    min: 1,
    max: 5,
    step: 1,
    initialValue: 3,
  },
  {
    type: "evidencias",
    key: "documentacionRelevanciaEvidencias",
    namePrefix: "documentacionRelevancia",
    fields: [
      { name: "documentacionRelevanciaEvidencia1", initialValue: "" },
      { name: "documentacionRelevanciaEvidencia2", initialValue: "" },
      { name: "documentacionRelevanciaEvidencia3", initialValue: "" },
    ],
  },
  {
    type: "sectionTitle",
    key: "evaluacionRelacionPoliticas",
    title: "Evaluación de Relación con Políticas",
  },
  {
    type: "slider",
    key: "evaluacionRelacionPoliticasPregunta",
    label: "Califique (1-5) ¿En qué medida la dependencia encargada de la operación estadística asegura que los resultados de la operación estadística están alineados con las políticas públicas establecidas?",
    name: "evaluacionRelacionPoliticasPregunta",
    min: 1,
    max: 5,
    step: 1,
    initialValue: 3,
  },
  {
    type: "evidencias",
    key: "evaluacionRelacionPoliticasEvidencias",
    namePrefix: "evaluacionRelacionPoliticas",
    fields: [
      { name: "evaluacionRelacionPoliticasEvidencia1", initialValue: "" },
      { name: "evaluacionRelacionPoliticasEvidencia2", initialValue: "" },
      { name: "evaluacionRelacionPoliticasEvidencia3", initialValue: "" },
    ],
  },
  {
    type: "sectionTitle",
    key: "revisionActualizacionRelevancia",
    title: "Revisión y Actualización de Relevancia",
  },
  {
    type: "radio",
    key: "revisionActualizacionRelevanciaPregunta",
    label: "¿Cómo evalúa la dependencia encargada de la operación estadística la revisión y actualización de la relevancia de los resultados de la operación estadística en función de cambios en las políticas públicas?",
    name: "revisionActualizacionRelevanciaPregunta",
    options: ["Sí", "No"],
    initialValue: "Sí",
  },
  {
    type: "textarea",
    key: "revisionActualizacionRelevanciaDescripcion",
    label: "Si la respuesta es Sí, ¿qué mecanismos se utilizan para esta revisión? (Describa brevemente)",
    name: "revisionActualizacionRelevanciaDescripcion",
    placeholder: "Describa brevemente los mecanismos utilizados...",
    initialValue: "",
  },
  {
    type: "evidencias",
    key: "revisionActualizacionRelevanciaEvidencias",
    namePrefix: "revisionActualizacionRelevancia",
    fields: [
      { name: "revisionActualizacionRelevanciaEvidencia1", initialValue: "" },
      { name: "revisionActualizacionRelevanciaEvidencia2", initialValue: "" },
      { name: "revisionActualizacionRelevanciaEvidencia3", initialValue: "" },
    ],
  },
  {
    type: "sectionTitle",
    key: "sugerenciasRelevanciaOperaciones",
    title: "Sugerencias para Mejorar la Relevancia de las Operaciones Estadísticas en la Política Pública",
  },
  {
    type: "sugerencias",
    key: "sugerenciasRelevanciaOperacionesPregunta",
    label: "¿Tiene alguna sugerencia o comentario sobre cómo la entidad podría mejorar la identificación, documentación y evidencia de la relevancia de sus operaciones estadísticas en relación con la política pública?",
    name: "sugerenciasRelevanciaOperacionesPregunta",
    initialValue: "",
  },
  {
    type: "sectionTitle",
    key: "accionesRequeridas",
    title: "Acciones requeridas",
  },
  {
    type: "accionesRequeridas",
    key: "accionesRequeridas",
    fields: [
      { name: "accion", initialValue: "" },
      { name: "responsableSNS", initialValue: "" },
      { name: "fechaCumplimiento", initialValue: "" },
    ],
  },
];
