export const questions5_4 = [
  {
    type: "sectionTitle",
    key: "determinacionObjetivosGeneralesEspecificos",
    title: "Determinación de los Objetivos Generales y Específicos",
  },
  {
    type: "slider",
    key: "determinacionObjetivosGeneralesEspecificosPregunta",
    label: "Califique de 1-5 ¿En qué medida la dependencia encargada de la operación estadística determina adecuadamente los objetivos generales y específicos para esta operación estadística?",
    name: "determinacionObjetivosGeneralesEspecificosPregunta",
    min: 1,
    max: 5,
    step: 1,
    initialValue: 2,
  },
  {
    type: "evidencias",
    key: "determinacionObjetivosGeneralesEspecificosEvidencias",
    namePrefix: "determinacionObjetivosGeneralesEspecificos",
    fields: [
      { name: "determinacionObjetivosGeneralesEspecificosEvidencia1", initialValue: "" },
      { name: "determinacionObjetivosGeneralesEspecificosEvidencia2", initialValue: "" },
      { name: "determinacionObjetivosGeneralesEspecificosEvidencia3", initialValue: "" },
    ],
  },
  {
    type: "sectionTitle",
    key: "congruenciaObjetivosNecesidadesInfo",
    title: "Congruencia de los Objetivos con las Necesidades de Información",
  },
  {
    type: "slider",
    key: "congruenciaObjetivosNecesidadesInfoPregunta",
    label: "Califique de 1-5 ¿Qué tan bien están alineados los objetivos de la operación estadística con las necesidades de información que se pretenden satisfacer?",
    name: "congruenciaObjetivosNecesidadesInfoPregunta",
    min: 1,
    max: 5,
    step: 1,
    initialValue: 2,
  },
  {
    type: "evidencias",
    key: "congruenciaObjetivosNecesidadesInfoEvidencias",
    namePrefix: "congruenciaObjetivosNecesidadesInfo",
    fields: [
      { name: "congruenciaObjetivosNecesidadesInfoEvidencia1", initialValue: "" },
      { name: "congruenciaObjetivosNecesidadesInfoEvidencia2", initialValue: "" },
      { name: "congruenciaObjetivosNecesidadesInfoEvidencia3", initialValue: "" },
    ],
  },
  {
    type: "sectionTitle",
    key: "capacidadSeguimientoMedicionObjetivos",
    title: "Capacidad de Seguimiento y Medición de los Objetivos",
  },
  {
    type: "slider",
    key: "capacidadSeguimientoMedicionObjetivosPregunta",
    label: "Califique de 1-5 ¿En qué medida los objetivos definidos permiten un seguimiento y medición efectivos?",
    name: "capacidadSeguimientoMedicionObjetivosPregunta",
    min: 1,
    max: 5,
    step: 1,
    initialValue: 2,
  },
  {
    type: "evidencias",
    key: "capacidadSeguimientoMedicionObjetivosEvidencias",
    namePrefix: "capacidadSeguimientoMedicionObjetivos",
    fields: [
      { name: "capacidadSeguimientoMedicionObjetivosEvidencia1", initialValue: "" },
      { name: "capacidadSeguimientoMedicionObjetivosEvidencia2", initialValue: "" },
      { name: "capacidadSeguimientoMedicionObjetivosEvidencia3", initialValue: "" },
    ],
  },
  {
    type: "sectionTitle",
    key: "comunicacionObjetivosPartesInteresadas",
    title: "Comunicación de los Objetivos a las Partes Interesadas",
  },
  {
    type: "slider",
    key: "comunicacionObjetivosPartesInteresadasPregunta",
    label: "Califique de 1-5 ¿Cómo evalúa la efectividad de la dependencia encargada de la operación estadística en comunicar los objetivos de la operación estadística a todas las partes interesadas (internas y externas)?",
    name: "comunicacionObjetivosPartesInteresadasPregunta",
    min: 1,
    max: 5,
    step: 1,
    initialValue: 2,
  },
  {
    type: "evidencias",
    key: "comunicacionObjetivosPartesInteresadasEvidencias",
    namePrefix: "comunicacionObjetivosPartesInteresadas",
    fields: [
      { name: "comunicacionObjetivosPartesInteresadasEvidencia1", initialValue: "" },
      { name: "comunicacionObjetivosPartesInteresadasEvidencia2", initialValue: "" },
      { name: "comunicacionObjetivosPartesInteresadasEvidencia3", initialValue: "" },
    ],
  },
  {
    type: "sectionTitle",
    key: "actualizacionObjetivos",
    title: "Actualización de los Objetivos",
  },
  {
    type: "slider",
    key: "actualizacionObjetivosPregunta",
    label: "Califique de 1-5 ¿En qué medida la dependencia encargada de la operación estadística actualiza los objetivos cuando cambian las necesidades de información o el objeto de estudio?",
    name: "actualizacionObjetivosPregunta",
    min: 1,
    max: 5,
    step: 1,
    initialValue: 2,
  },
  {
    type: "evidencias",
    key: "actualizacionObjetivosEvidencias",
    namePrefix: "actualizacionObjetivos",
    fields: [
      { name: "actualizacionObjetivosEvidencia1", initialValue: "" },
      { name: "actualizacionObjetivosEvidencia2", initialValue: "" },
      { name: "actualizacionObjetivosEvidencia3", initialValue: "" },
    ],
  },
  {
    type: "sectionTitle",
    key: "mejorarGestionObjetivosOperacionesEstadisticas",
    title: "Mejorar la Gestión de Objetivos en las Operaciones Estadísticas",
  },
  {
    type: "sugerencias",
    key: "mejorarGestionObjetivosOperacionesEstadisticasPregunta",
    label: "¿Tiene alguna sugerencia o comentario sobre cómo la entidad podría mejorar la determinación, comunicación y actualización de los objetivos en las operaciones estadísticas?",
    name: "mejorarGestionObjetivosOperacionesEstadisticasPregunta",
    initialValue: "",
  },
  {
    type: "sectionTitle",
    key: "accionesRequeridas",
    title: "Acciones requeridas",
  },
  {
    type: "accionesRequeridas",
    key: "accionesRequeridas",
    fields: [
      { name: "accion", initialValue: "" },
      { name: "responsableSNS", initialValue: "" },
      { name: "fechaCumplimiento", initialValue: "" },
    ],
  },
];
