export const questions4_7 = [
  {
    type: "sectionTitle",
    key: "identificacionRiesgos",
    title: "Identificación de Riesgos",
  },
  {
    type: "radio",
    key: "identificacionRiesgosPregunta",
    label: "¿La entidad identifica y analiza adecuadamente los riesgos del proceso estadístico?",
    name: "identificacionRiesgosPregunta",
    options: ["Sí", "No"],
    initialValue: "Sí",
  },
  {
    type: "radio",
    key: "identificacionRiesgosDetalleA",
    label: "Si la respuesta es Sí, ¿la identificación de riesgos incluye una evaluación detallada de los posibles riesgos?",
    name: "identificacionRiesgosDetalleA",
    options: ["Sí", "No"],
    initialValue: "Sí",
  },
  {
    type: "radio",
    key: "identificacionRiesgosDetalleB",
    label: "Si la respuesta es Sí, ¿la identificación de riesgos incluye un análisis de la probabilidad y el impacto de cada riesgo?",
    name: "identificacionRiesgosDetalleB",
    options: ["Sí", "No"],
    initialValue: "Sí",
  },
  {
    type: "radio",
    key: "identificacionRiesgosDetalleC",
    label: "Si la respuesta es Sí, ¿la identificación de riesgos incluye una clasificación de los riesgos en función de su gravedad?",
    name: "identificacionRiesgosDetalleC",
    options: ["Sí", "No"],
    initialValue: "Sí",
  },
  {
    type: "evidencias",
    key: "identificacionRiesgosEvidencias",
    namePrefix: "identificacionRiesgos",
    fields: [
      { name: "identificacionRiesgosEvidencia1", initialValue: "" },
      { name: "identificacionRiesgosEvidencia2", initialValue: "" },
      { name: "identificacionRiesgosEvidencia3", initialValue: "" },
    ],
  },
  {
    type: "sectionTitle",
    key: "implementacionControles",
    title: "Implementación de controles",
  },
  {
    type: "radio",
    key: "implementacionControlesPregunta",
    label: "¿La entidad implementa controles para minimizar los riesgos identificados en el proceso estadístico?",
    name: "implementacionControlesPregunta",
    options: ["Sí", "No"],
    initialValue: "Sí",
  },
  {
    type: "checkbox",
    key: "implementacionControlesUtiliza",
    label: "Si la respuesta es Sí, ¿cuáles de los siguientes controles utiliza la entidad? Seleccione todas las opciones que correspondan:",
    name: "implementacionControlesUtiliza",
    options: [
      "Medidas preventivas",
      "Procedimientos de mitigación",
      "Planes de contingencia",
      "Revisiones periódicas",
      "Auditorías internas",
      "Capacitación del personal",
      "Establecimiento de responsabilidades claras",
    ],
    initialValue: [],
  },
  {
    type: "evidencias",
    key: "implementacionControlesEvidencias",
    namePrefix: "implementacionControles",
    fields: [
      { name: "implementacionControlesEvidencia1", initialValue: "" },
      { name: "implementacionControlesEvidencia2", initialValue: "" },
      { name: "implementacionControlesEvidencia3", initialValue: "" },
    ],
  },
  {
    type: "sectionTitle",
    key: "accionesMaterializacionRiesgos",
    title: "Acciones ante la Materialización de Riesgos",
  },
  {
    type: "slider",
    key: "accionesMaterializacionRiesgosPregunta",
    label: "Califique (1-5) qué tan efectiva es la entidad en tomar acciones cuando los riesgos se materializan en el proceso estadístico.",
    name: "accionesMaterializacionRiesgosPregunta",
    min: 1,
    max: 5,
    step: 1,
    initialValue: 2,
  },
  {
    type: "evidencias",
    key: "accionesMaterializacionRiesgosEvidencias",
    namePrefix: "accionesMaterializacionRiesgos",
    fields: [
      { name: "accionesMaterializacionRiesgosEvidencia1", initialValue: "" },
      { name: "accionesMaterializacionRiesgosEvidencia2", initialValue: "" },
      { name: "accionesMaterializacionRiesgosEvidencia3", initialValue: "" },
    ],
  },
  {
    type: "sectionTitle",
    key: "riesgosControles",
    title: "Riesgos y Controles",
  },
  {
    type: "slider",
    key: "riesgosControlesPregunta",
    label: "Califique (1-5) en qué medida la entidad documenta y mantiene la información sobre los riesgos identificados y los controles implementados.",
    name: "riesgosControlesPregunta",
    min: 1,
    max: 5,
    step: 1,
    initialValue: 2,
  },
  {
    type: "evidencias",
    key: "riesgosControlesEvidencias",
    namePrefix: "riesgosControles",
    fields: [
      { name: "riesgosControlesEvidencia1", initialValue: "" },
      { name: "riesgosControlesEvidencia2", initialValue: "" },
      { name: "riesgosControlesEvidencia3", initialValue: "" },
    ],
  },
  {
    type: "sectionTitle",
    key: "revisionActualizacionRiesgos",
    title: "Revisión y Actualización de Riesgos",
  },
  {
    type: "slider",
    key: "revisionActualizacionRiesgosPregunta",
    label: "¿Cómo evalúa (1-5) los procesos que aplica la entidad para la revisión y actualización periódica de los riesgos y controles en el proceso estadístico, según lo especificado en su documentación de gestión de riesgos?",
    name: "revisionActualizacionRiesgosPregunta",
    min: 1,
    max: 5,
    step: 1,
    initialValue: 2,
  },
  {
    type: "evidencias",
    key: "revisionActualizacionRiesgosEvidencias",
    namePrefix: "revisionActualizacionRiesgos",
    fields: [
      { name: "revisionActualizacionRiesgosEvidencia1", initialValue: "" },
      { name: "revisionActualizacionRiesgosEvidencia2", initialValue: "" },
      { name: "revisionActualizacionRiesgosEvidencia3", initialValue: "" },
    ],
  },
  {
    type: "sectionTitle",
    key: "sugerenciasGestionRiesgos",
    title: "Sugerencias para Gestión de los Riesgos",
  },
  {
    type: "sugerencias",
    key: "sugerenciasGestionRiesgosPregunta",
    label: "¿Tiene alguna sugerencia o comentario sobre cómo la entidad podría mejorar la identificación, análisis, control y respuesta a los riesgos en el proceso estadístico?",
    name: "sugerenciasGestionRiesgosPregunta",
    initialValue: "",
  },
  {
    type: "sectionTitle",
    key: "accionesRequeridas",
    title: "Acciones requeridas",
  },
  {
    type: "accionesRequeridas",
    key: "accionesRequeridas",
    fields: [
      { name: "accion", initialValue: "" },
      { name: "responsableSNS", initialValue: "" },
      { name: "fechaCumplimiento", initialValue: "" },
    ],
  },
];
