export const questions5_2 = [
  {
    type: "sectionTitle",
    key: "analisisNecesidadesRecolectadas",
    title: "Análisis de las Necesidades Recolectadas",
  },
  {
    type: "slider",
    key: "analisisNecesidadesRecolectadasPregunta",
    label: "Califique (1-5) ¿En qué medida la entidad analiza adecuadamente las necesidades de los usuarios en función del área temática, el alcance de la operación estadística, la normatividad y los recursos disponibles?",
    name: "analisisNecesidadesRecolectadasPregunta",
    min: 1,
    max: 5,
    step: 1,
    initialValue: 2,
  },
  {
    type: "checkbox",
    key: "analisisNecesidadesRecolectadasDetalle",
    label: "Este análisis incluye:",
    name: "analisisNecesidadesRecolectadasDetalle",
    options: [
      "El área temática de estudio",
      "El alcance previsto para la operación estadística",
      "La normatividad (si aplica)",
      "Los recursos",
    ],
    initialValue: [],
  },
  {
    type: "evidencias",
    key: "analisisNecesidadesRecolectadasEvidencias",
    namePrefix: "analisisNecesidadesRecolectadas",
    fields: [
      { name: "analisisNecesidadesRecolectadasEvidencia1", initialValue: "" },
      { name: "analisisNecesidadesRecolectadasEvidencia2", initialValue: "" },
      { name: "analisisNecesidadesRecolectadasEvidencia3", initialValue: "" },
    ],
  },
  {
    type: "sectionTitle",
    key: "documentacionConservacionNecesidadesPrioritarias",
    title: "Documentación y Conservación de Necesidades Prioritarias",
  },
  {
    type: "slider",
    key: "documentacionConservacionNecesidadesPrioritariasPregunta",
    label: "Califique (1-5) ¿Qué tan efectiva es la entidad en documentar y conservar las necesidades priorizadas de los usuarios según los criterios establecidos?",
    name: "documentacionConservacionNecesidadesPrioritariasPregunta",
    min: 1,
    max: 5,
    step: 1,
    initialValue: 2,
  },
  {
    type: "evidencias",
    key: "documentacionConservacionNecesidadesPrioritariasEvidencias",
    namePrefix: "documentacionConservacionNecesidadesPrioritarias",
    fields: [
      { name: "documentacionConservacionNecesidadesPrioritariasEvidencia1", initialValue: "" },
      { name: "documentacionConservacionNecesidadesPrioritariasEvidencia2", initialValue: "" },
      { name: "documentacionConservacionNecesidadesPrioritariasEvidencia3", initialValue: "" },
    ],
  },
  {
    type: "sectionTitle",
    key: "consultaConfirmacionNecesidadesPrioritarias",
    title: "Consulta y Confirmación de Necesidades Prioritarias con los Usuarios",
  },
  {
    type: "slider",
    key: "consultaConfirmacionNecesidadesPrioritariasPregunta",
    label: "¿Cómo evalúa (1-5) a la entidad en la consulta y confirmación de las necesidades prioritarias con los usuarios?",
    name: "consultaConfirmacionNecesidadesPrioritariasPregunta",
    min: 1,
    max: 5,
    step: 1,
    initialValue: 2,
  },
  {
    type: "evidencias",
    key: "consultaConfirmacionNecesidadesPrioritariasEvidencias",
    namePrefix: "consultaConfirmacionNecesidadesPrioritarias",
    fields: [
      { name: "consultaConfirmacionNecesidadesPrioritariasEvidencia1", initialValue: "" },
      { name: "consultaConfirmacionNecesidadesPrioritariasEvidencia2", initialValue: "" },
      { name: "consultaConfirmacionNecesidadesPrioritariasEvidencia3", initialValue: "" },
    ],
  },
  {
    type: "sectionTitle",
    key: "comunicacionNecesidadesConsideradas",
    title: "Comunicación a los Usuarios sobre las Necesidades Consideradas y No Consideradas",
  },
  {
    type: "slider",
    key: "comunicacionNecesidadesConsideradasPregunta",
    label: "Califique (1-5) en qué medida la entidad informa adecuadamente a los usuarios sobre las necesidades que fueron priorizadas y aquellas que no fueron consideradas.",
    name: "comunicacionNecesidadesConsideradasPregunta",
    min: 1,
    max: 5,
    step: 1,
    initialValue: 2,
  },
  {
    type: "evidencias",
    key: "comunicacionNecesidadesConsideradasEvidencias",
    namePrefix: "comunicacionNecesidadesConsideradas",
    fields: [
      { name: "comunicacionNecesidadesConsideradasEvidencia1", initialValue: "" },
      { name: "comunicacionNecesidadesConsideradasEvidencia2", initialValue: "" },
      { name: "comunicacionNecesidadesConsideradasEvidencia3", initialValue: "" },
    ],
  },
  {
    type: "sectionTitle",
    key: "sugerenciasAnalisisNecesidadesRecolectadas",
    title: "Sugerencias para Análisis de las Necesidades Recogidas",
  },
  {
    type: "sugerencias",
    key: "sugerenciasAnalisisNecesidadesRecolectadasPregunta",
    label: "¿Tiene alguna sugerencia o comentario sobre cómo la entidad podría mejorar el análisis, la documentación, la confirmación y la conservación de las necesidades de información estadística recolectadas de los usuarios?",
    name: "sugerenciasAnalisisNecesidadesRecolectadasPregunta",
    initialValue: "",
  },
  {
    type: "sectionTitle",
    key: "accionesRequeridas",
    title: "Acciones requeridas",
  },
  {
    type: "accionesRequeridas",
    key: "accionesRequeridas",
    fields: [
      { name: "accion", initialValue: "" },
      { name: "responsableSNS", initialValue: "" },
      { name: "fechaCumplimiento", initialValue: "" },
    ],
  },
];
