export const questions4_6 = [
  {
    type: "sectionTitle",
    key: "implementacionBuenasPracticas",
    title: "Implementación de Buenas Prácticas Estadísticas",
  },
  {
    type: "radio",
    key: "implementacionBuenasPracticasPregunta",
    label: "¿La dependencia encargada de la operación estadística asegura que en el proceso estadístico se implementan las buenas prácticas estadísticas, los estándares estadísticos o geográficos y los lineamientos emitidos por el DANE?",
    name: "implementacionBuenasPracticasPregunta",
    options: ["Sí", "No"],
    initialValue: "",
  },
  {
    type: "checkbox",
    key: "implementacionBuenasPracticasIncluye",
    label: "Si la respuesta es Sí, ¿se incluye en la implementación los siguientes elementos? Seleccione todas las opciones que correspondan:",
    name: "implementacionBuenasPracticasIncluye",
    options: [
      "Conceptos Estadísticos",
      "Variables Estadísticas",
      "Nomenclaturas y Clasificaciones",
      "Unidades Estadísticas",
    ],
    initialValue: [],
  },
  {
    type: "evidencias",
    key: "implementacionBuenasPracticasEvidencias",
    namePrefix: "implementacionBuenasPracticas",
    fields: [
      { name: "implementacionBuenasPracticasEvidencia1", initialValue: "" },
      { name: "implementacionBuenasPracticasEvidencia2", initialValue: "" },
      { name: "implementacionBuenasPracticasEvidencia3", initialValue: "" },
    ],
  },
  {
    type: "sectionTitle",
    key: "usoEstandaresEstadisticos",
    title: "Uso de Estándares Estadísticos",
  },
  {
    type: "radio",
    key: "usoEstandaresEstadisticosPregunta",
    label: "¿La dependencia encargada de la operación estadística utiliza estándares estadísticos emitidos por el DANE, y en caso de no estar disponibles, emplea estándares nacionales o internacionales?",
    name: "usoEstandaresEstadisticosPregunta",
    options: ["Sí", "No"],
    initialValue: "",
  },
  {
    type: "slider",
    key: "usoEstandaresEstadisticosCalificacion",
    label: "Si la respuesta es Sí, Califique de 1-5 ¿Qué tanto se asegura la articulación con el entorno estadístico internacional?",
    name: "usoEstandaresEstadisticosCalificacion",
    min: 1,
    max: 5,
    step: 1,
    initialValue: 3,
  },
  {
    type: "evidencias",
    key: "usoEstandaresEstadisticosEvidencias",
    namePrefix: "usoEstandaresEstadisticos",
    fields: [
      { name: "usoEstandaresEstadisticosEvidencia1", initialValue: "" },
      { name: "usoEstandaresEstadisticosEvidencia2", initialValue: "" },
      { name: "usoEstandaresEstadisticosEvidencia3", initialValue: "" },
    ],
  },
  {
    type: "sectionTitle",
    key: "documentacionAplicacionEstandares",
    title: "Documentación y Aplicación de Estándares",
  },
  {
    type: "slider",
    key: "documentacionAplicacionEstandaresPregunta",
    label: "Califique (1-5) ¿Qué tan efectiva es la dependencia encargada de la operación estadística en la documentación y aplicación de los estándares estadísticos en el proceso estadístico?",
    name: "documentacionAplicacionEstandaresPregunta",
    min: 1,
    max: 5,
    step: 1,
    initialValue: 3,
  },
  {
    type: "evidencias",
    key: "documentacionAplicacionEstandaresEvidencias",
    namePrefix: "documentacionAplicacionEstandares",
    fields: [
      { name: "documentacionAplicacionEstandaresEvidencia1", initialValue: "" },
      { name: "documentacionAplicacionEstandaresEvidencia2", initialValue: "" },
      { name: "documentacionAplicacionEstandaresEvidencia3", initialValue: "" },
    ],
  },
  {
    type: "sectionTitle",
    key: "comparabilidadInteroperabilidad",
    title: "Comparabilidad e Interoperabilidad",
  },
  {
    type: "slider",
    key: "comparabilidadInteroperabilidadPregunta",
    label: "Califique (1-5) en qué medida la dependencia encargada de la operación estadística asegura la comparabilidad, integración e interoperabilidad en el uso de los estándares estadísticos?",
    name: "comparabilidadInteroperabilidadPregunta",
    min: 1,
    max: 5,
    step: 1,
    initialValue: 3,
  },
  {
    type: "evidencias",
    key: "comparabilidadInteroperabilidadEvidencias",
    namePrefix: "comparabilidadInteroperabilidad",
    fields: [
      { name: "comparabilidadInteroperabilidadEvidencia1", initialValue: "" },
      { name: "comparabilidadInteroperabilidadEvidencia2", initialValue: "" },
      { name: "comparabilidadInteroperabilidadEvidencia3", initialValue: "" },
    ],
  },
  {
    type: "sectionTitle",
    key: "evaluacionEstandaresEstadisticos",
    title: "Evaluación de Estándares Estadísticos",
  },
  {
    type: "slider",
    key: "evaluacionEstandaresEstadisticosPregunta",
    label: "¿Cómo evalúa de 1 a 5? la dependencia encargada de la operación estadística la aplicación de los estándares estadísticos en relación con los lineamientos emitidos por el DANE y los estándares internacionales?",
    name: "evaluacionEstandaresEstadisticosPregunta",
    min: 1,
    max: 5,
    step: 1,
    initialValue: 3,
  },
  {
    type: "evidencias",
    key: "evaluacionEstandaresEstadisticosEvidencias",
    namePrefix: "evaluacionEstandaresEstadisticos",
    fields: [
      { name: "evaluacionEstandaresEstadisticosEvidencia1", initialValue: "" },
      { name: "evaluacionEstandaresEstadisticosEvidencia2", initialValue: "" },
      { name: "evaluacionEstandaresEstadisticosEvidencia3", initialValue: "" },
    ],
  },
  {
    type: "sectionTitle",
    key: "sugerenciasUsoLineamientos",
    title: "Sugerencias para Uso y Aplicación de Lineamientos Estadísticos",
  },
  {
    type: "sugerencias",
    key: "sugerenciasUsoLineamientosPregunta",
    label: "¿Tiene alguna sugerencia o comentario sobre cómo la entidad podría mejorar la implementación, aplicación y documentación de los lineamientos y estándares estadísticos en el proceso estadístico?",
    name: "sugerenciasUsoLineamientosPregunta",
    initialValue: "",
  },
  {
    type: "sectionTitle",
    key: "accionesRequeridas",
    title: "Acciones requeridas",
  },
  {
    type: "accionesRequeridas",
    key: "accionesRequeridas",
    fields: [
      { name: "accion", initialValue: "" },
      { name: "responsableSNS", initialValue: "" },
      { name: "fechaCumplimiento", initialValue: "" },
    ],
  },
];
