export const questions4_4 = [
  {
    type: "sectionTitle",
    key: "documentacionMetodologica",
    title: "Documentación Metodológica y de Soporte",
  },
  {
    type: "radio",
    key: "documentacionMetodologicaPregunta",
    label: "¿La dependencia encargada de la operación estadística elabora, implementa, conserva y actualiza adecuadamente el documento metodológico y la ficha metodológica?",
    name: "documentacionMetodologicaPregunta",
    options: ["Sí", "No", "No Aplica"],
    initialValue: "",
  },
  {
    type: "checkbox",
    key: "documentacionMetodologicaIncluye",
    label: "Si la respuesta es Sí, la documentación incluye. Seleccione todas las opciones que correspondan:",
    name: "documentacionMetodologicaIncluye",
    options: [
      "Manuales",
      "Procedimientos",
      "Guías",
      "Instructivos",
      "Especificaciones",
      "Fichas Técnicas",
      "Otros Documentos",
    ],
    initialValue: [],
  },
  {
    type: "sectionTitle",
    key: "disponibilidadDocumentacion",
    title: "Disponibilidad de la Documentación",
  },
  {
    type: "radio",
    key: "disponibilidadDocumentacionPregunta",
    label: "¿La dependencia encargada de la operación estadística asegura que toda la documentación (como el documento metodológico y otros documentos de soporte) esté disponible para su uso antes de iniciar la fase de recolección o acopio?",
    name: "disponibilidadDocumentacionPregunta",
    options: ["Sí", "No"],
    initialValue: "",
  },
  {
    type: "evidencias",
    key: "disponibilidadDocumentacionEvidencias",
    namePrefix: "disponibilidadDocumentacion",
    fields: [
      { name: "disponibilidadDocumentacionEvidencia1", initialValue: "" },
      { name: "disponibilidadDocumentacionEvidencia2", initialValue: "" },
      { name: "disponibilidadDocumentacionEvidencia3", initialValue: "" },
    ],
  },
  {
    type: "sectionTitle",
    key: "conservacionEvidencia",
    title: "Conservación y Evidencia del Proceso Estadístico",
  },
  {
    type: "slider",
    key: "conservacionEvidenciaPregunta",
    label: "Califique (1-5) ¿Qué tan efectiva es la dependencia encargada de la operación estadística en conservar la información documentada que evidencia la implementación del proceso estadístico, como formatos diligenciados, registros, actas, videograbaciones, entre otros?",
    name: "conservacionEvidenciaPregunta",
    min: 1,
    max: 5,
    step: 1,
    initialValue: 3,
  },
  {
    type: "evidencias",
    key: "conservacionEvidenciaEvidencias",
    namePrefix: "conservacionEvidencia",
    fields: [
      { name: "conservacionEvidenciaEvidencia1", initialValue: "" },
      { name: "conservacionEvidenciaEvidencia2", initialValue: "" },
      { name: "conservacionEvidenciaEvidencia3", initialValue: "" },
    ],
  },
  {
    type: "sectionTitle",
    key: "identificacionDescripcion",
    title: "Identificación y Descripción de la Información Documentada",
  },
  {
    type: "slider",
    key: "identificacionDescripcionPregunta",
    label: "Califique (1-5) ¿En qué medida la dependencia encargada de la operación estadística asegura que la identificación y descripción de la información documentada sea apropiada, según los procedimientos establecidos en el sistema de gestión de la entidad?",
    name: "identificacionDescripcionPregunta",
    min: 1,
    max: 5,
    step: 1,
    initialValue: 3,
  },
  {
    type: "evidencias",
    key: "identificacionDescripcionEvidencias",
    namePrefix: "identificacionDescripcion",
    fields: [
      { name: "identificacionDescripcionEvidencia1", initialValue: "" },
      { name: "identificacionDescripcionEvidencia2", initialValue: "" },
      { name: "identificacionDescripcionEvidencia3", initialValue: "" },
    ],
  },
  {
    type: "sectionTitle",
    key: "controlProteccionInformacion",
    title: "Control y Protección de la Información Documentada",
  },
  {
    type: "textarea",
    key: "controlProteccionPregunta",
    label: "¿Cómo evalúa la dependencia encargada de la operación estadística el control y protección de la información documentada, asegurando su disponibilidad, idoneidad, protección adecuada, distribución, acceso, recuperación, almacenamiento, preservación, conservación y actualización?",
    name: "controlProteccionPregunta",
    placeholder: "Ingrese su evaluación",
    rows: 4,
    initialValue: "",
  },
  {
    type: "evidencias",
    key: "controlProteccionEvidencias",
    namePrefix: "controlProteccion",
    fields: [
      { name: "controlProteccionEvidencia1", initialValue: "" },
      { name: "controlProteccionEvidencia2", initialValue: "" },
      { name: "controlProteccionEvidencia3", initialValue: "" },
    ],
  },
  {
    type: "sectionTitle",
    key: "sugerenciasInformacionDocumentada",
    title: "Sugerencias para Información Documentada del Proceso Estadístico",
  },
  {
    type: "sugerencias",
    key: "sugerenciasInformacionDocumentadaPregunta",
    label: "¿Tiene alguna sugerencia o comentario sobre cómo la entidad podría mejorar la identificación, documentación y actualización de los usuarios y sus necesidades de información estadística?",
    name: "sugerenciasInformacionDocumentadaPregunta",
    initialValue: "",
  },
  {
    type: "sectionTitle",
    key: "accionesRequeridas",
    title: "Acciones requeridas",
  },
  {
    type: "accionesRequeridas",
    key: "accionesRequeridas",
    fields: [
      { name: "accion", initialValue: "" },
      { name: "responsableSNS", initialValue: "" },
      { name: "fechaCumplimiento", initialValue: "" },
    ],
  },
];
