export const questions4_8 = [
  {
    type: "sectionTitle",
    key: "implementacionFasesProcesoEstadistico",
    title: "Implementación de las Fases del Proceso Estadístico",
  },
  {
    type: "checkbox",
    key: "implementacionFasesProcesoEstadisticoPregunta",
    label: "La dependencia encargada de la operación estadística asegura que se implementen adecuadamente todas las fases del proceso estadístico, que incluye:",
    name: "implementacionFasesProcesoEstadisticoPregunta",
    options: [
      "Detección y análisis de necesidades",
      "Diseño",
      "Construcción",
      "Recolección o acopio",
      "Procesamiento",
      "Análisis",
      "Difusión",
      "Evaluación",
    ],
    initialValue: [],
  },
  {
    type: "evidencias",
    key: "implementacionFasesProcesoEstadisticoEvidencias",
    namePrefix: "implementacionFasesProcesoEstadistico",
    fields: [
      { name: "implementacionFasesProcesoEstadisticoEvidencia1", initialValue: "" },
      { name: "implementacionFasesProcesoEstadisticoEvidencia2", initialValue: "" },
      { name: "implementacionFasesProcesoEstadisticoEvidencia3", initialValue: "" },
    ],
  },
  {
    type: "sectionTitle",
    key: "cumplimientoFasesProcesoEstadistico",
    title: "Cumplimiento de las Fases del Proceso Estadístico",
  },
  {
    type: "radio",
    key: "cumplimientoFasesProcesoEstadisticoPregunta",
    label: "¿La dependencia encargada de la operación estadística sigue la descripción del proceso estadístico según el numeral 0.2 de la norma?",
    name: "cumplimientoFasesProcesoEstadisticoPregunta",
    options: ["Sí", "No"],
    initialValue: "",
  },
  {
    type: "slider",
    key: "cumplimientoFasesProcesoEstadisticoCalificacion",
    label: "Si la respuesta es Sí, ¿en qué medida cumple la entidad con cada una de las fases del proceso estadístico? (1-5)",
    name: "cumplimientoFasesProcesoEstadisticoCalificacion",
    min: 1,
    max: 5,
    step: 1,
    initialValue: 3,
  },
  {
    type: "evidencias",
    key: "cumplimientoFasesProcesoEstadisticoEvidencias",
    namePrefix: "cumplimientoFasesProcesoEstadistico",
    fields: [
      { name: "cumplimientoFasesProcesoEstadisticoEvidencia1", initialValue: "" },
      { name: "cumplimientoFasesProcesoEstadisticoEvidencia2", initialValue: "" },
      { name: "cumplimientoFasesProcesoEstadisticoEvidencia3", initialValue: "" },
    ],
  },
  {
    type: "sectionTitle",
    key: "efectividadImplementacionProcesoEstadistico",
    title: "Efectividad en la Implementación del Proceso Estadístico",
  },
  {
    type: "slider",
    key: "efectividadImplementacionProcesoEstadisticoPregunta",
    label: "Califique (1-5) ¿Qué tan efectiva es la dependencia encargada de la operación estadística en la implementación de cada fase del proceso estadístico?",
    name: "efectividadImplementacionProcesoEstadisticoPregunta",
    min: 1,
    max: 5,
    step: 1,
    initialValue: 3,
  },
  {
    type: "evidencias",
    key: "efectividadImplementacionProcesoEstadisticoEvidencias",
    namePrefix: "efectividadImplementacionProcesoEstadistico",
    fields: [
      { name: "efectividadImplementacionProcesoEstadisticoEvidencia1", initialValue: "" },
      { name: "efectividadImplementacionProcesoEstadisticoEvidencia2", initialValue: "" },
      { name: "efectividadImplementacionProcesoEstadisticoEvidencia3", initialValue: "" },
    ],
  },
  {
    type: "sectionTitle",
    key: "documentacionAplicacionFasesProcesoEstadistico",
    title: "Documentación y Aplicación de las fases del Proceso Estadístico",
  },
  {
    type: "slider",
    key: "documentacionAplicacionFasesProcesoEstadisticoPregunta",
    label: "Califique (1-5) ¿En qué medida la dependencia encargada de la operación estadística documenta y aplica las fases del proceso estadístico?",
    name: "documentacionAplicacionFasesProcesoEstadisticoPregunta",
    min: 1,
    max: 5,
    step: 1,
    initialValue: 3,
  },
  {
    type: "evidencias",
    key: "documentacionAplicacionFasesProcesoEstadisticoEvidencias",
    namePrefix: "documentacionAplicacionFasesProcesoEstadistico",
    fields: [
      { name: "documentacionAplicacionFasesProcesoEstadisticoEvidencia1", initialValue: "" },
      { name: "documentacionAplicacionFasesProcesoEstadisticoEvidencia2", initialValue: "" },
      { name: "documentacionAplicacionFasesProcesoEstadisticoEvidencia3", initialValue: "" },
    ],
  },
  {
    type: "sectionTitle",
    key: "revisionActualizacionProcesoEstadistico",
    title: "Revisión y Actualización del Proceso Estadístico",
  },
  {
    type: "slider",
    key: "revisionActualizacionProcesoEstadisticoPregunta",
    label: "¿Cómo evalúa la dependencia encargada de la operación estadística la revisión y actualización periódica del proceso estadístico para asegurar la mejora continua? (1 = Muy Insuficiente, 5 = Muy Satisfactoria).",
    name: "revisionActualizacionProcesoEstadisticoPregunta",
    min: 1,
    max: 5,
    step: 1,
    initialValue: 3,
  },
  {
    type: "evidencias",
    key: "revisionActualizacionProcesoEstadisticoEvidencias",
    namePrefix: "revisionActualizacionProcesoEstadistico",
    fields: [
      { name: "revisionActualizacionProcesoEstadisticoEvidencia1", initialValue: "" },
      { name: "revisionActualizacionProcesoEstadisticoEvidencia2", initialValue: "" },
      { name: "revisionActualizacionProcesoEstadisticoEvidencia3", initialValue: "" },
    ],
  },
  {
    type: "sectionTitle",
    key: "sugerenciasImplementacionProcesoEstadistico",
    title: "Sugerencias para Implementación del Proceso Estadístico",
  },
  {
    type: "sugerencias",
    key: "sugerenciasImplementacionProcesoEstadisticoPregunta",
    label: "¿Tiene alguna sugerencia o comentario sobre cómo la entidad podría mejorar la identificación, documentación y actualización de los usuarios y sus necesidades de información estadística?",
    name: "sugerenciasImplementacionProcesoEstadisticoPregunta",
    initialValue: "",
  },
  {
    type: "sectionTitle",
    key: "accionesRequeridas",
    title: "Acciones requeridas",
  },
  {
    type: "accionesRequeridas",
    key: "accionesRequeridas",
    fields: [
      { name: "accion", initialValue: "" },
      { name: "responsableSNS", initialValue: "" },
      { name: "fechaCumplimiento", initialValue: "" },
    ],
  },
];
