export const questions5_1 = [
  {
    type: "sectionTitle",
    key: "identificacionUsuariosRelevantes",
    title: "Identificación de Usuarios Relevantes",
  },
  {
    type: "radio",
    key: "identificacionUsuariosRelevantesPregunta",
    label: "¿La entidad identifica adecuadamente a los usuarios internos y externos que tienen necesidades de información estadística?",
    name: "identificacionUsuariosRelevantesPregunta",
    options: ["Sí", "No"],
    initialValue: "0",
  },
  {
    type: "checkbox",
    key: "identificacionUsuariosRelevantesDetalle",
    label: "Si la respuesta es Sí, la identificación incluye:",
    name: "identificacionUsuariosRelevantesDetalle",
    options: [
      "Nombre de la persona y los datos de identificación de la entidad u organización",
      "Datos de contacto",
      "El sector o la temática a la que pertenece",
    ],
    initialValue: [],
  },
  {
    type: "evidencias",
    key: "identificacionUsuariosRelevantesEvidencias",
    namePrefix: "identificacionUsuariosRelevantes",
    fields: [
      { name: "identificacionUsuariosRelevantesEvidencia1", initialValue: "" },
      { name: "identificacionUsuariosRelevantesEvidencia2", initialValue: "" },
      { name: "identificacionUsuariosRelevantesEvidencia3", initialValue: "" },
    ],
  },
  {
    type: "sectionTitle",
    key: "mecanismosConsultaUsuarios",
    title: "Mecanismos de Consulta a Usuarios",
  },
  {
    type: "radio",
    key: "mecanismosConsultaUsuariosPregunta",
    label: "¿La entidad define, implementa y mantiene los mecanismos de consulta que permiten obtener y analizar las necesidades de información de los usuarios?",
    name: "mecanismosConsultaUsuariosPregunta",
    options: ["Sí", "No"],
    initialValue: "0",
  },
  {
    type: "checkbox",
    key: "mecanismosConsultaUsuariosMetodos",
    label: "Si la respuesta es Sí, ¿Cuáles de los siguientes mecanismos de consulta utiliza la Entidad para la identificación de usuarios y sus necesidades de información estadística? Seleccione todas las opciones que correspondan.",
    name: "mecanismosConsultaUsuariosMetodos",
    options: [
      "Encuestas",
      "Reuniones con expertos en la temática de la operación estadística",
      "Reuniones de trabajo con partes interesadas especializadas",
      "Mesas intersectoriales",
      "Solicitudes directas de información estadística",
      "Documentos de política pública",
      "Planes (estratégicos, acción, o de mejora)",
      "Consultas de referentes (nacionales o internacionales)",
    ],
    initialValue: [],
  },
  {
    type: "evidencias",
    key: "mecanismosConsultaUsuariosEvidencias",
    namePrefix: "mecanismosConsultaUsuarios",
    fields: [
      { name: "mecanismosConsultaUsuariosEvidencia1", initialValue: "" },
      { name: "mecanismosConsultaUsuariosEvidencia2", initialValue: "" },
      { name: "mecanismosConsultaUsuariosEvidencia3", initialValue: "" },
    ],
  },
  {
    type: "sectionTitle",
    key: "documentacionConservacionInfoUsuarios",
    title: "Documentación y Conservación de la Información de Usuarios",
  },
  {
    type: "slider",
    key: "documentacionConservacionInfoUsuariosPregunta",
    label: "Califique (1-5) qué tan efectiva es la entidad en documentar, conservar y actualizar la información de identificación de los usuarios.",
    name: "documentacionConservacionInfoUsuariosPregunta",
    min: 1,
    max: 5,
    step: 1,
    initialValue: 2,
  },
  {
    type: "evidencias",
    key: "documentacionConservacionInfoUsuariosEvidencias",
    namePrefix: "documentacionConservacionInfoUsuarios",
    fields: [
      { name: "documentacionConservacionInfoUsuariosEvidencia1", initialValue: "" },
      { name: "documentacionConservacionInfoUsuariosEvidencia2", initialValue: "" },
      { name: "documentacionConservacionInfoUsuariosEvidencia3", initialValue: "" },
    ],
  },
  {
    type: "sectionTitle",
    key: "identificacionDocumentacionNecesidadesInfo",
    title: "Identificación y Documentación de Necesidades de Información",
  },
  {
    type: "slider",
    key: "identificacionDocumentacionNecesidadesInfoPregunta",
    label: "¿Califique (1-5) en qué medida la entidad identifica, documenta y conserva las necesidades de información estadística de los usuarios identificados?",
    name: "identificacionDocumentacionNecesidadesInfoPregunta",
    min: 1,
    max: 5,
    step: 1,
    initialValue: 2,
  },
  {
    type: "evidencias",
    key: "identificacionDocumentacionNecesidadesInfoEvidencias",
    namePrefix: "identificacionDocumentacionNecesidadesInfo",
    fields: [
      { name: "identificacionDocumentacionNecesidadesInfoEvidencia1", initialValue: "" },
      { name: "identificacionDocumentacionNecesidadesInfoEvidencia2", initialValue: "" },
      { name: "identificacionDocumentacionNecesidadesInfoEvidencia3", initialValue: "" },
    ],
  },
  {
    type: "sectionTitle",
    key: "revisionActualizacionNecesidadesInfo",
    title: "Revisión y Actualización de Necesidades de Información",
  },
  {
    type: "slider",
    key: "revisionActualizacionNecesidadesInfoPregunta",
    label: "¿Cómo evalúa (1-5) la forma en la que la entidad hace la revisión y actualización periódica de las necesidades de información de los usuarios, según lo especificado en el documento metodológico de la operación estadística?",
    name: "revisionActualizacionNecesidadesInfoPregunta",
    min: 1,
    max: 5,
    step: 1,
    initialValue: 2,
  },
  {
    type: "evidencias",
    key: "revisionActualizacionNecesidadesInfoEvidencias",
    namePrefix: "revisionActualizacionNecesidadesInfo",
    fields: [
      { name: "revisionActualizacionNecesidadesInfoEvidencia1", initialValue: "" },
      { name: "revisionActualizacionNecesidadesInfoEvidencia2", initialValue: "" },
      { name: "revisionActualizacionNecesidadesInfoEvidencia3", initialValue: "" },
    ],
  },
  {
    type: "sectionTitle",
    key: "sugerenciasMejorarIdentificacionUsuariosNecesidadesInfo",
    title: "Sugerencias para mejorar la Identificación de Usuarios y Necesidades de Información",
  },
  {
    type: "sugerencias",
    key: "sugerenciasMejorarIdentificacionUsuariosNecesidadesInfoPregunta",
    label: "¿Tiene alguna sugerencia o comentario sobre cómo la entidad podría mejorar la identificación, documentación y actualización de los usuarios y sus necesidades de información estadística?",
    name: "sugerenciasMejorarIdentificacionUsuariosNecesidadesInfoPregunta",
    initialValue: "",
  },
  {
    type: "sectionTitle",
    key: "accionesRequeridas",
    title: "Acciones requeridas",
  },
  {
    type: "accionesRequeridas",
    key: "accionesRequeridas",
    fields: [
      { name: "accion", initialValue: "" },
      { name: "responsableSNS", initialValue: "" },
      { name: "fechaCumplimiento", initialValue: "" },
    ],
  },
];
