export const questions4_5 = [
  {
    type: "sectionTitle",
    key: "determinacionProvisionPersonal",
    title: "Determinación y Provisión de Personal",
  },
  {
    type: "radio",
    key: "determinacionProvisionPersonalPregunta",
    label: "¿La dependencia encargada de la operación estadística determina y proporciona el personal necesario para cumplir los objetivos de la operación estadística, así como para la implementación, el mantenimiento y la mejora continua del proceso estadístico?",
    name: "determinacionProvisionPersonalPregunta",
    options: ["Sí", "No"],
    initialValue: "Sí",
  },
  {
    type: "evidencias",
    key: "determinacionProvisionPersonalEvidencias",
    namePrefix: "determinacionProvisionPersonal",
    fields: [
      { name: "determinacionProvisionPersonalEvidencia1", initialValue: "" },
      { name: "determinacionProvisionPersonalEvidencia2", initialValue: "" },
      { name: "determinacionProvisionPersonalEvidencia3", initialValue: "" },
    ],
  },
  {
    type: "sectionTitle",
    key: "competenciaPersonal",
    title: "Competencia del Personal",
  },
  {
    type: "radio",
    key: "competenciaPersonalPregunta1",
    label: "¿La dependencia encargada de la operación estadística determina los perfiles necesarios para desarrollar el proceso estadístico y conserva los registros que demuestran que el personal cumple con dichos perfiles?",
    name: "competenciaPersonalPregunta1",
    options: ["Sí", "No"],
    initialValue: "Sí",
  },
  {
    type: "radio",
    key: "competenciaPersonalPregunta2",
    label: "Si la respuesta es Sí, ¿la dependencia encargada de la operación estadística también implementa y documenta acciones de entrenamiento para asegurar la competencia del personal involucrado en el desarrollo de la operación estadística?",
    name: "competenciaPersonalPregunta2",
    options: ["Sí", "No"],
    initialValue: "Sí",
  },
  {
    type: "evidencias",
    key: "competenciaPersonalEvidencias",
    namePrefix: "competenciaPersonal",
    fields: [
      { name: "competenciaPersonalEvidencia1", initialValue: "" },
      { name: "competenciaPersonalEvidencia2", initialValue: "" },
      { name: "competenciaPersonalEvidencia3", initialValue: "" },
    ],
  },
  {
    type: "sectionTitle",
    key: "efectividadMantenimientoRegistros",
    title: "Efectividad en el Mantenimiento de Registros",
  },
  {
    type: "slider",
    key: "efectividadMantenimientoRegistrosPregunta",
    label: "Califique (1-5) ¿Qué tan efectiva es la dependencia encargada de la operación estadística en conservar los registros que demuestran que el personal cumple con los perfiles necesarios para el proceso estadístico?",
    name: "efectividadMantenimientoRegistrosPregunta",
    min: 1,
    max: 5,
    step: 1,
    initialValue: 3,
  },
  {
    type: "evidencias",
    key: "efectividadMantenimientoRegistrosEvidencias",
    namePrefix: "efectividadMantenimientoRegistros",
    fields: [
      { name: "efectividadMantenimientoRegistrosEvidencia1", initialValue: "" },
      { name: "efectividadMantenimientoRegistrosEvidencia2", initialValue: "" },
      { name: "efectividadMantenimientoRegistrosEvidencia3", initialValue: "" },
    ],
  },
  {
    type: "sectionTitle",
    key: "implementacionAccionesEntrenamiento",
    title: "Implementación de Acciones de Entrenamiento",
  },
  {
    type: "slider",
    key: "implementacionAccionesEntrenamientoPregunta",
    label: "Califique (1-5) ¿En qué medida la dependencia encargada de la operación estadística determina, implementa y documenta acciones de entrenamiento para asegurar la competencia del personal en el desarrollo de la operación estadística?",
    name: "implementacionAccionesEntrenamientoPregunta",
    min: 1,
    max: 5,
    step: 1,
    initialValue: 3,
  },
  {
    type: "evidencias",
    key: "implementacionAccionesEntrenamientoEvidencias",
    namePrefix: "implementacionAccionesEntrenamiento",
    fields: [
      { name: "implementacionAccionesEntrenamientoEvidencia1", initialValue: "" },
      { name: "implementacionAccionesEntrenamientoEvidencia2", initialValue: "" },
      { name: "implementacionAccionesEntrenamientoEvidencia3", initialValue: "" },
    ],
  },
  {
    type: "sectionTitle",
    key: "cumplimientoPerfiles",
    title: "Cumplimiento de Perfiles",
  },
  {
    type: "slider",
    key: "cumplimientoPerfilesPregunta",
    label: "Califique de 1-5 ¿Cómo evalúa la dependencia encargada de la operación estadística la adecuación del personal a los perfiles determinados para el proceso estadístico?",
    name: "cumplimientoPerfilesPregunta",
    min: 1,
    max: 5,
    step: 1,
    initialValue: 3,
  },
  {
    type: "evidencias",
    key: "cumplimientoPerfilesEvidencias",
    namePrefix: "cumplimientoPerfiles",
    fields: [
      { name: "cumplimientoPerfilesEvidencia1", initialValue: "" },
      { name: "cumplimientoPerfilesEvidencia2", initialValue: "" },
      { name: "cumplimientoPerfilesEvidencia3", initialValue: "" },
    ],
  },
  {
    type: "sectionTitle",
    key: "sugerenciasPersonalProcesoEstadistico",
    title: "Sugerencias para Personal del Proceso Estadístico",
  },
  {
    type: "sugerencias",
    key: "sugerenciasPersonalProcesoEstadisticoPregunta",
    label: "¿Tiene alguna sugerencia o comentario sobre cómo la entidad podría mejorar la identificación, documentación y actualización de los usuarios y sus necesidades de información estadística?",
    name: "sugerenciasPersonalProcesoEstadisticoPregunta",
    initialValue: "",
  },
  {
    type: "sectionTitle",
    key: "accionesRequeridas",
    title: "Acciones requeridas",
  },
  {
    type: "accionesRequeridas",
    key: "accionesRequeridas",
    fields: [
      { name: "accion", initialValue: "" },
      { name: "responsableSNS", initialValue: "" },
      { name: "fechaCumplimiento", initialValue: "" },
    ],
  },
];
